# Generated by Django 5.1.3 on 2025-03-17 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ic_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ic_colour', models.CharField(blank=True, max_length=1, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_back', 'Sent Back to Employee'), ('dean_review', 'Dean Review'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Contract Status')),
                ('present_post', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_scale_division', models.CharField(blank=True, max_length=50, null=True)),
                ('incremental_date', models.DateField(blank=True, null=True)),
                ('date_of_last_appraisal', models.DateField(blank=True, null=True)),
                ('academic_qualifications_text', models.TextField(blank=True, null=True)),
                ('current_enrollment', models.TextField(blank=True, null=True)),
                ('higher_degree_students_supervised', models.TextField(blank=True, null=True)),
                ('last_research', models.JSONField(blank=True, null=True)),
                ('ongoing_research', models.JSONField(blank=True, null=True)),
                ('publications', models.JSONField(blank=True, null=True)),
                ('attendance', models.TextField(blank=True, null=True)),
                ('conference_papers', models.JSONField(blank=True, null=True)),
                ('consultancy_work', models.JSONField(blank=True, null=True)),
                ('administrative_posts', models.TextField(blank=True, null=True)),
                ('participation_within_text', models.TextField(blank=True, null=True)),
                ('participation_outside_text', models.TextField(blank=True, null=True)),
                ('objectives_next_year', models.TextField(blank=True, null=True)),
                ('appraiser_comments', models.TextField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('RENEWAL_3', 'Renewal of contract (3 years)'), ('EXTENSION_1', 'Extension of current contract (1 year)'), ('LOCAL_RENEWAL', 'New/Renewal of contract for local staff'), ('OTHER', 'Other')], default='RENEWAL_3', max_length=20, verbose_name='Type of contract applied')),
                ('teaching_modules_text', models.TextField(blank=True, null=True)),
                ('teaching_future_plan', models.TextField(blank=True, null=True, verbose_name='Teaching Future Plan')),
                ('achievements_last_contract', models.TextField(blank=True, verbose_name='What have you achieved in the last contract for Teaching / Research / Administrative Duties?')),
                ('achievements_proposal', models.TextField(blank=True, verbose_name='What do you propose to undertake and achieve if your contract is renewed?')),
                ('other_matters', models.TextField(blank=True, verbose_name='Any other matters you wish to highlight?')),
                ('teaching_documents', models.BinaryField(blank=True, null=True)),
                ('teaching_documents_name', models.CharField(blank=True, max_length=255, null=True)),
                ('university_committees_text', models.TextField(blank=True, null=True)),
                ('external_committees_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_date', models.DateTimeField(auto_now=True)),
                ('contract_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Contract Renewal Statuses',
            },
        ),
        migrations.CreateModel(
            name='DeanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('document', models.BinaryField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMTReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('sent_back', 'Sent Back to Employee'), ('dean_review', 'Dean Review'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField()),
                ('document', models.BinaryField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
