# Generated by Django 5.1.3 on 2025-03-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisals', '0002_initial'),
        ('contract', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='memberships',
            field=models.ManyToManyField(blank=True, to='appraisals.membership'),
        ),
        migrations.AddField(
            model_name='contract',
            name='modules_taught',
            field=models.ManyToManyField(blank=True, to='appraisals.module'),
        ),
        migrations.AddField(
            model_name='administrativeposition',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_positions', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='contractnotification',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
        migrations.AddField(
            model_name='contractnotification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='contractrenewalstatus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='deanreview',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dean_reviews', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='deanreview',
            name='dean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dean_reviews', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='smtreview',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smt_reviews', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='smtreview',
            name='smt_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smt_reviews', to='employees.employee'),
        ),
    ]
