# Generated by Django 5.1.3 on 2025-02-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='conference_papers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='consultancy_work',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='last_research',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ongoing_research',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
