# Generated by Django 5.1.3 on 2025-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_back', 'Sent Back to Employee'), ('dean_review', 'Dean Review'), ('smt_review', 'Currently under SMT Review'), ('smt_approved', 'Approved by SMT'), ('smt_rejected', 'Rejected by SMT'), ('moe_review', 'Currently under MOE Review'), ('moe_approved', 'Approved by MOE'), ('moe_rejected', 'Rejected by MOE')], default='pending', max_length=20, verbose_name='Contract Status'),
        ),
        migrations.AlterField(
            model_name='smtreview',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_back', 'Sent Back to Employee'), ('dean_review', 'Dean Review'), ('smt_review', 'Currently under SMT Review'), ('smt_approved', 'Approved by SMT'), ('smt_rejected', 'Rejected by SMT'), ('moe_review', 'Currently under MOE Review'), ('moe_approved', 'Approved by MOE'), ('moe_rejected', 'Rejected by MOE')], max_length=20),
        ),
    ]
