# Generated by Django 5.1.3 on 2024-11-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_appraisal_contract_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='appraisal',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='current_post',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='research_details',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
