# Generated by Django 5.1.3 on 2025-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_conference_papers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='publications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
