# Generated by Django 5.1.3 on 2024-11-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_administrative_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='administrative_posts',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='conference_papers',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='consultancy_work',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='last_research',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ongoing_research',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='present_post',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='salary_scale_division',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
