# Generated by Django 5.1.3 on 2025-02-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_conferencepaper_consultancywork_ongoingresearch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancywork',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='ongoingresearch',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='researchhistory',
            name='contract',
        ),
        migrations.DeleteModel(
            name='ConferencePaper',
        ),
        migrations.DeleteModel(
            name='ConsultancyWork',
        ),
        migrations.DeleteModel(
            name='OngoingResearch',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='ResearchHistory',
        ),
    ]
