# Generated by Django 5.1.3 on 2025-03-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_consultancywork_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hr_comments',
            field=models.TextField(blank=True, help_text='Comments from HR when sending back the form', null=True, verbose_name='HR Comments'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_back', 'Sent Back for Revision')], default='pending', max_length=20, verbose_name='Contract Status'),
        ),
    ]
