# Generated by Django 5.1.3 on 2025-04-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_peerreview'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_contracts', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
