# Generated by Django 5.1.3 on 2025-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_contract_draft_saved_at_contract_draft_saved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='draft_saved_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='draft_saved_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_draft',
        ),
    ]
