# Generated by Django 5.1.3 on 2024-11-28 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_contract_options_remove_contract_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='administrative_posts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='conference_papers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='consultancy_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_research',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ongoing_research',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='present_post',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='publications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary_scale_division',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
