# Generated by Django 5.1.3 on 2025-04-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_contract_draft_saved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='administrative_positions_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fellowships_awards_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
