# Generated by Django 5.1.3 on 2025-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_contract_hr_comments_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hr_comments',
            field=models.TextField(blank=True, null=True, verbose_name='HR Comments'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_back', 'Sent Back to Employee')], default='pending', max_length=20, verbose_name='Contract Status'),
        ),
    ]
