# Generated by Django 5.1.3 on 2025-04-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_administrative_positions_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='administrative_positions_text',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='fellowships_awards_text',
        ),
    ]
