# Generated by Django 5.1.3 on 2025-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_hr_comments_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='hr_comments',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Contract Status'),
        ),
    ]
