# Generated by Django 5.1.3 on 2025-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_remove_contract_administrative_positions_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='fellowships_awards_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
