# Generated by Django 5.1.3 on 2024-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_remove_appraisal_academic_qualifications_and_more'),
        ('contract', '0010_alter_contract_options_remove_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='academic_qualifications_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='current_enrollment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_of_last_appraisal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='higher_degree_students_supervised',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='incremental_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='memberships',
            field=models.ManyToManyField(blank=True, to='appraisals.membership'),
        ),
        migrations.AddField(
            model_name='contract',
            name='modules_taught',
            field=models.ManyToManyField(blank=True, to='appraisals.module'),
        ),
        migrations.AddField(
            model_name='contract',
            name='objectives_next_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='participation_outside_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='participation_within_university',
            field=models.TextField(blank=True, null=True),
        ),
    ]
