# Generated by Django 5.1.3 on 2025-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_contract_fellowships_awards_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='mentorship_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='supervision_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
