# Generated by Django 5.1.3 on 2025-03-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
