# Generated by Django 5.1.3 on 2024-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_academic_qualifications_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='academic_staff_same_field',
            field=models.TextField(blank=True, help_text='Names of Academic Staff in the same field (within UBD only)', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='achievements_last_contract',
            field=models.TextField(blank=True, help_text='What have you achieved in the last contract?', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='activities_outside_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='activities_within_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_department_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_faculty_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_outside_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='consultancy_current',
            field=models.TextField(blank=True, help_text='Consultancy undertaken within CURRENT contract', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('renewal_3', 'Renewal of contract (3 years)'), ('extension_1', 'Extension of current contract (1 year)'), ('renewal_local', 'New/Renewal of contract for local staff'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type_other',
            field=models.CharField(blank=True, help_text='Please specify if contract type is Other', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='current_basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='current_contract_duration',
            field=models.CharField(blank=True, help_text='E.g. 3 years (25 May 2020 to 24 May 2023)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='current_contract_number',
            field=models.IntegerField(blank=True, help_text='Number of current contract', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='field_of_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_of_kin',
            field=models.TextField(blank=True, help_text='Name, relationship, citizenship and contact number', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='office_extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_matters',
            field=models.TextField(blank=True, help_text='Any other matters you wish to highlight?', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='performance_history',
            field=models.TextField(blank=True, help_text='Performance Appraisal last 3 years [Year (mark, grade)]', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='programme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposed_achievements',
            field=models.TextField(blank=True, help_text='What do you propose to undertake and achieve if your contract is renewed?', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='publications_current',
            field=models.TextField(blank=True, help_text='Publications in CURRENT contract', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='publications_forthcoming',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='research_current_contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='research_project_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
