# Generated by Django 5.1.3 on 2025-04-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_mentorship_text_contract_supervision_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='mentorship_text',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='supervision_text',
        ),
    ]
