# Generated by Django 5.1.3 on 2024-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_contract_academic_staff_same_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='academic_staff_same_field',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='achievements_last_contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='activities_outside_university',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='activities_within_university',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='admin_department_level',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='admin_faculty_level',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='admin_outside_university',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='admin_university',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='consultancy_current',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_type_other',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='current_basic_salary',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='current_contract_duration',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='current_contract_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='field_of_specialization',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='office_extension',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='other_matters',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='performance_history',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='proposed_achievements',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='publications_current',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='publications_forthcoming',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='research_current_contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='research_project_status',
        ),
    ]
