# Generated by Django 5.1.3 on 2025-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_remove_contract_mentorship_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='grad_supervision_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='mentorship_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
