# Generated by Django 5.1.3 on 2025-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_populate_contract_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
