# Generated by Django 5.1.3 on 2024-11-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_remove_contract_academic_staff_same_field_and_more'),
        ('employees', '0006_employee_ic_colour_employee_ic_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ic_colour',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ic_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
