# Generated by Django 5.1.3 on 2025-05-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_contract_grad_supervision_text_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_contracts', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
