# Generated by Django 5.1.3 on 2025-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_alter_contract_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
