# Generated by Django 5.1.3 on 2025-03-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_alter_contract_contract_id'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('revise', 'Request Revision')], max_length=20)),
                ('document', models.BinaryField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dean_reviews', to='contract.contract')),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dean_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
