# Generated by Django 5.1.3 on 2024-11-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_contract_department_contract_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ic_colour',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ic_no',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='phone_number',
        ),
    ]
