# Generated by Django 5.1.3 on 2025-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_contract_draft_saved_at_contract_draft_saved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
