# Generated by Django 5.1.3 on 2025-03-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_deanreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_back', 'Sent Back to Employee'), ('dean_review', 'Dean Review'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Contract Status'),
        ),
    ]
