# Generated by Django 5.1.3 on 2025-03-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deanreview',
            name='recommendation',
        ),
    ]
