# Generated by Django 5.1.3 on 2024-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_contract_department_contract_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='appraisee_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Appraisee Comments'),
        ),
    ]
