# Generated by Django 5.1.3 on 2025-03-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_remove_deanreview_recommendation'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('sent_back', 'Sent Back to Employee'), ('dean_review', 'Dean Review'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField()),
                ('document', models.BinaryField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smt_reviews', to='contract.contract')),
                ('smt_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smt_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
