# Generated by Django 5.1.3 on 2024-11-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_contract_appraisee_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='appraisee_comments',
        ),
    ]
