# Generated by Django 5.1.3 on 2024-11-28 11:07

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_remove_appraisal_academic_qualifications_and_more'),
        ('contract', '0020_contract_department_contract_first_name_and_more'),
        ('employees', '0006_employee_ic_colour_employee_ic_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('employee', 'submission_date')},
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('submission_date__gt', django.db.models.expressions.CombinedExpression(models.F('submission_date'), '-', models.Value(datetime.timedelta(days=180))))), name='one_submission_per_six_months'),
        ),
    ]
