# Generated by Django 5.1.3 on 2024-11-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_remove_appraisal_academic_qualifications_and_more'),
        ('contract', '0021_alter_contract_unique_together_and_more'),
        ('employees', '0006_employee_ic_colour_employee_ic_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='one_submission_per_six_months',
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employee', 'submission_date'], name='contract_co_employe_7e17c5_idx'),
        ),
    ]
