# Generated by Django 5.1.3 on 2024-11-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_remove_contract_one_submission_per_six_months_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_co_employe_7e17c5_idx',
        ),
    ]
