# Generated by Django 5.1.3 on 2024-11-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0029_contractnotification_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractNotification',
        ),
    ]
