# Generated by Django 5.1.3 on 2024-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0031_contractnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnotification',
            name='notification_type',
            field=models.CharField(choices=[('HR_SENT', 'HR Sent Notification'), ('EMPLOYEE_RECEIVED', 'Employee Received Notification')], default='HR_SENT', max_length=20),
        ),
    ]
