# Generated by Django 5.1.3 on 2024-11-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_contractnotification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractnotification',
            name='notification_type',
        ),
    ]
