# Generated by Django 5.1.3 on 2024-11-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0033_remove_contractnotification_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractNotification',
        ),
    ]
