# Generated by Django 5.1.3 on 2024-11-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0037_contractnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractNotification',
        ),
    ]
