# Generated by Django 5.1.3 on 2024-11-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0041_contractrenewalnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractRenewalNotification',
        ),
    ]
