# Generated by Django 5.1.3 on 2024-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0043_contractnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrenewalstatus',
            name='contract_count',
            field=models.IntegerField(default=1),
        ),
    ]
