# Generated by Django 5.1.3 on 2024-12-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0046_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('smt_review', 'SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='PENDING', max_length=20, verbose_name='Contract Status'),
        ),
    ]
