# Generated by Django 5.1.3 on 2024-12-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0047_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('RENEWAL_3', 'Renewal of contract (3 years)'), ('EXTENSION_1', 'Extension of current contract (1 year)'), ('LOCAL_RENEWAL', 'New/Renewal of contract for local staff'), ('OTHER', 'Other')], default='RENEWAL_3', max_length=20, verbose_name='Type of contract applied'),
        ),
    ]
