# Generated by Django 5.1.3 on 2024-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0049_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('smt_review', 'Currently under SMT Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Contract Status'),
        ),
    ]
