# Generated by Django 5.1.3 on 2024-12-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0050_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='research_projects',
            field=models.TextField(blank=True),
        ),
    ]
