# Generated by Django 5.1.3 on 2024-12-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0051_contract_research_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='research_projects',
        ),
    ]
