# Generated by Django 5.1.3 on 2024-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0052_remove_contract_research_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_matters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposed_achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
