# Generated by Django 5.1.3 on 2024-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_contract_achievements_contract_other_matters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='other_matters',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='proposed_achievements',
        ),
    ]
