# Generated by Django 5.1.3 on 2024-12-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0054_remove_contract_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_matters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposed_achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
