# Generated by Django 5.1.3 on 2024-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0056_remove_contract_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='last_contract_achievements',
            field=models.TextField(blank=True, verbose_name='Achievements in last contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_matters',
            field=models.TextField(blank=True, verbose_name='Other matters'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposed_achievements',
            field=models.TextField(blank=True, verbose_name='Proposed achievements for renewal'),
        ),
    ]
