# Generated by Django 5.1.3 on 2024-12-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0057_contract_last_contract_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='last_contract_achievements',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='other_matters',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='proposed_achievements',
        ),
    ]
