# Generated by Django 5.1.3 on 2024-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0058_remove_contract_last_contract_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='achievements_last_contract',
            field=models.TextField(blank=True, verbose_name='What have you achieved in the last contract for Teaching / Research / Administrative Duties?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='achievements_proposal',
            field=models.TextField(blank=True, verbose_name='What do you propose to undertake and achieve if your contract is renewed?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_matters',
            field=models.TextField(blank=True, verbose_name='Any other matters you wish to highlight?'),
        ),
    ]
