# Generated by Django 5.1.3 on 2024-12-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0060_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
