# Generated by Django 5.1.3 on 2024-12-03 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0062_remove_contractnotification_employee_and_more'),
        ('employees', '0006_employee_ic_colour_employee_ic_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractnotification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='contractnotification',
            name='user',
        ),
        migrations.AddField(
            model_name='contractnotification',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
