# Generated by Django 5.1.3 on 2024-12-03 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0063_remove_contractnotification_link_and_more'),
        ('employees', '0006_employee_ic_colour_employee_ic_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnotification',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractnotification',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
