# Generated by Django 5.1.3 on 2024-12-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0064_contractnotification_contract_and_more'),
        ('employees', '0007_employee_contract_renewal_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnotification',
            name='notification_type',
            field=models.CharField(choices=[('submission', 'Form Submission'), ('renewal_due', 'Renewal Due')], default='submission', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractnotification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractnotification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
