# Generated by Django 5.1.3 on 2024-12-03 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0065_contractnotification_notification_type_and_more'),
        ('employees', '0008_remove_employee_contract_renewal_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractnotification',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='contractnotification',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractnotification',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
