# Generated by Django 5.1.3 on 2024-12-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0066_remove_contractnotification_notification_type_and_more'),
        ('employees', '0008_remove_employee_contract_renewal_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractnotification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
