# Generated by Django 5.1.3 on 2024-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0067_alter_contractnotification_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnotification',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
