# Generated by Django 5.1.3 on 2025-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0068_contractnotification_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='teaching_modules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
