# Generated by Django 5.1.3 on 2025-02-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0069_contract_teaching_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='teaching_modules',
        ),
    ]
