# Generated by Django 5.1.3 on 2025-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0070_remove_contract_teaching_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='teaching_modules_text',
            field=models.TextField(blank=True, help_text='JSON string containing teaching modules information', null=True),
        ),
    ]
