# Generated by Django 5.1.3 on 2025-02-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0071_contract_teaching_modules_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='teaching_modules_text',
        ),
    ]
