# Generated by Django 5.1.3 on 2025-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0075_contract_teaching_modules_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='teaching_future_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Teaching Future Plan'),
        ),
    ]
