# Generated by Django 5.1.3 on 2025-02-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0076_contract_teaching_future_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='participation_outside_university',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='participation_within_university',
        ),
        migrations.AddField(
            model_name='contract',
            name='participation_outside_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='participation_within_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
