# Generated by Django 5.1.3 on 2025-02-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0077_remove_contract_participation_outside_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='teaching_documents_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
