# Generated by Django 5.1.3 on 2025-02-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0078_contract_teaching_documents_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='teaching_documents_text',
        ),
    ]
