# Generated by Django 5.1.3 on 2025-02-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0079_remove_contract_teaching_documents_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='teaching_documents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
