# Generated by Django 5.1.3 on 2025-02-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0082_contract_teaching_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='teaching_documents',
        ),
    ]
