# Generated by Django 5.1.3 on 2025-02-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0083_remove_contract_teaching_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='teaching_documents',
            field=models.FileField(blank=True, null=True, upload_to='contract_documents/teaching/%Y/%m/', verbose_name='Teaching Documents'),
        ),
    ]
