# Generated by Django 5.1.3 on 2025-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0084_contract_teaching_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='teaching_documents_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='teaching_documents',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
