# Generated by Django 5.1.3 on 2025-02-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0085_contract_teaching_documents_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('details', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_positions', to='contract.contract')),
            ],
        ),
    ]
