# Generated by Django 5.1.3 on 2025-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0086_administrativeposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='external_committees_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='university_committees_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
