# Generated by Django 4.2.19 on 2025-04-27 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_philosophy_full', models.TextField(blank=True)),
                ('teaching_philosophy_summary', models.TextField(blank=True)),
                ('learning_outcome_full', models.TextField(blank=True)),
                ('learning_outcome_summary', models.TextField(blank=True)),
                ('instructional_methodology_full', models.TextField(blank=True)),
                ('instructional_methodology_summary', models.TextField(blank=True)),
                ('other_means_to_enhance_learning_full', models.TextField(blank=True)),
                ('other_means_to_enhance_learning_summary', models.TextField(blank=True)),
                ('other_teaching_full', models.TextField(blank=True)),
                ('academic_leadership_full', models.TextField(blank=True)),
                ('academic_leadership_summary', models.TextField(blank=True)),
                ('contribution_teaching_materials_full', models.TextField(blank=True)),
                ('contribution_teaching_materials_summary', models.TextField(blank=True)),
                ('future_teaching_goals_full', models.TextField(blank=True)),
                ('future_teaching_goals_summary', models.TextField(blank=True)),
                ('future_steps_improve_teaching_full', models.TextField(blank=True)),
                ('future_steps_improve_teaching_summary', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20, verbose_name='Module Code')),
                ('module_title', models.CharField(max_length=200, verbose_name='Module Title')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('semester', models.CharField(max_length=20, verbose_name='Semester')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Level')),
                ('number_of_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Students')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Role')),
                ('description', models.TextField(blank=True, verbose_name='Module Description')),
                ('hours_weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('language_medium', models.CharField(blank=True, max_length=100)),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('joint_teaching_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='teaching_portfolio.teachingportfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
