# Generated by Django 4.2.19 on 2025-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingportfolio',
            name='parsed_pdf_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
