# Generated by Django 5.1.3 on 2025-03-17 16:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, null=True)),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField(help_text='Date of hiring')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Employee salary', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('address', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('ic_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IC Number')),
                ('ic_colour', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('P', 'Purple'), ('G', 'Green'), ('R', 'Red')], max_length=1, null=True, verbose_name='IC Colour')),
                ('post', models.CharField(blank=True, help_text='Employee position/job title', max_length=100, null=True)),
                ('appointment_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Month-to-Month', 'Month-to-Month'), ('Daily-Rated', 'Daily-Rated')], help_text='Type of employment appointment', max_length=50, null=True)),
                ('scholar_id', models.CharField(blank=True, help_text='Google Scholar ID', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
                ('roles', models.ManyToManyField(blank=True, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=employees.models.employee_document_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_type', models.CharField(choices=[('book', 'Book'), ('article', 'Journal Article'), ('booklet', 'Booklet'), ('inbook', 'In Book'), ('incollection', 'In Collection'), ('inproceedings', 'Conference Paper'), ('manual', 'Manual'), ('mastersthesis', "Master's Thesis"), ('misc', 'Miscellaneous'), ('phdthesis', 'PhD Thesis'), ('proceedings', 'Conference Proceedings'), ('techreport', 'Technical Report'), ('unpublished', 'Unpublished Work')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_diploma', models.CharField(max_length=255)),
                ('university_college', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_qualifications', to='employees.employee')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employees_e_last_na_99a4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['ic_no'], name='employees_e_ic_no_ba3e85_idx'),
        ),
    ]
