# Generated by Django 5.1.3 on 2024-12-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='appointments',
        ),
    ]
