# Generated by Django 4.2.19 on 2025-04-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, choices=[('prof', 'Professor'), ('assoc_prof', 'Associate Professor')], help_text='Employee position/job title', max_length=50, null=True),
        ),
    ]
