# Generated by Django 5.1.3 on 2024-12-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Month-to-Month', 'Month-to-Month'), ('Daily-Rated', 'Daily-Rated')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_appointment_govt', models.DateField(blank=True, null=True)),
                ('first_appointment_ubd', models.DateField(blank=True, null=True)),
                ('post', models.CharField(max_length=100)),
                ('faculty_programme', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='employees.employee')),
                ('type_of_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.appointmenttype')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_of_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.appointmenttype', verbose_name='Type of Appointment'),
        ),
    ]
