# Generated by Django 5.1.3 on 2024-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_appointmenttype_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_diploma', models.CharField(max_length=100)),
                ('university_college', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='employees.qualification'),
        ),
    ]
