# Generated by Django 5.1.3 on 2024-12-02 14:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0004_qualification_alter_employee_qualifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['-to_date'], 'verbose_name': 'Qualification', 'verbose_name_plural': 'Qualifications'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type_of_appointment',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], help_text='Employee gender', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(help_text='Date of hiring'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, help_text='Employee position/job title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.qualification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Employee salary', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='degree_diploma',
            field=models.CharField(help_text='Name of degree or diploma', max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='from_date',
            field=models.DateField(help_text='Start date of study'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='to_date',
            field=models.DateField(help_text='Completion date'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='university_college',
            field=models.CharField(help_text='Institution name', max_length=100),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employees_e_last_na_99a4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['ic_no'], name='employees_e_ic_no_ba3e85_idx'),
        ),
    ]
