# Generated by Django 5.1.3 on 2024-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ic_colour',
            field=models.CharField(blank=True, choices=[('Y', 'Yellow'), ('P', 'Purple'), ('G', 'Green'), ('R', 'Red')], max_length=1, null=True, verbose_name='IC Colour'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ic_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IC Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='type_of_appointment',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Month-to-Month', 'Month-to-Month'), ('Daily Rated', 'Daily Rated')], max_length=50, null=True, verbose_name='Type of Appointment'),
        ),
    ]
