# Generated by Django 5.1.3 on 2024-12-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_options_alter_qualification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['-from_date']},
        ),
        migrations.AddField(
            model_name='qualification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_qualifications', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='degree_diploma',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='university_college',
            field=models.CharField(max_length=200),
        ),
    ]
