# Generated by Django 5.1.3 on 2024-12-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_qualification_options_qualification_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='faculty_programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.department', verbose_name='Faculty/Department'),
        ),
    ]
