# Generated by Django 5.1.3 on 2024-12-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0008_rename_appointments_appraisal_appointments_at_time_of_review_and_more'),
        ('employees', '0006_employee_ic_colour_employee_ic_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='appointments',
            field=models.ManyToManyField(blank=True, to='appraisals.appointment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='appraisals.qualification'),
        ),
    ]
