# Generated by Django 4.2.19 on 2025-06-03 01:36

from django.db import migrations

def create_departments(apps, schema_editor):
    Department = apps.get_model('employees', 'Department')
    departments_to_add = ['FOS', 'APB', 'IHS']
    for department_name in departments_to_add:
        Department.objects.get_or_create(name=department_name)

def reverse_departments(apps, schema_editor):
    Department = apps.get_model('employees', 'Department')
    departments_to_remove = ['FOS', 'APB', 'IHS']
    for department_name in departments_to_remove:
        # Only delete if no employees are linked to prevent errors
        try:
            department = Department.objects.get(name=department_name)
            if not department.employees.exists():
                department.delete()
        except Department.DoesNotExist:
            pass # Department doesn't exist, nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RunPython(create_departments, reverse_departments),
    ]
