# Generated by Django 5.1.3 on 2024-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_ic_colour_employee_ic_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_renewal_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
