# Generated by Django 5.1.3 on 2024-12-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_appointment_and_more'),
        ('employees', '0007_alter_appointment_faculty_programme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
