# Generated by Django 4.2.19 on 2025-06-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_add_initial_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, choices=[('prof', 'Professor'), ('assoc_prof', 'Associate Professor'), ('admin_officer', 'Administrative Officer'), ('education_officer', 'Education Officer'), ('program_coord', 'Program Coordinator'), ('research_assist', 'Research Assistant'), ('senior_lecturer', 'Senior Lecturer')], help_text='Employee position/job title', max_length=50, null=True),
        ),
    ]
