# Generated by Django 5.1.3 on 2024-12-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_contract_renewal_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract_renewal_enabled',
        ),
    ]
