# Generated by Django 5.1.3 on 2024-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=15),
        ),
    ]
