# Generated by Django 5.1.3 on 2024-12-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='appointment_type',
            field=models.ForeignKey(blank=True, help_text='Type of employment appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.appointmenttype'),
        ),
    ]
