# Generated by Django 4.2.19 on 2025-06-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, choices=[('prof', 'Professor'), ('assoc_prof', 'Associate Professor'), ('assist_registrar', 'Assistant Registrar'), ('lecturer', 'Lecturer'), ('admin officer', 'Administrative Officer'), ('education officer', 'Education Officer'), ('program coordinator', 'Program Coordinator'), ('research assistant', 'Research Assistant'), ('senior lecturer', 'Senior Lecturer')], help_text='Employee position/job title', max_length=50, null=True),
        ),
    ]
