# Generated by Django 5.1.3 on 2024-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree_diploma',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='university_college',
            field=models.CharField(max_length=255),
        ),
    ]
