# Generated by Django 5.1.3 on 2025-02-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_document_original_filename_alter_document_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Month-to-Month', 'Month-to-Month'), ('Daily-Rated', 'Daily-Rated')], help_text='Type of employment appointment', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AppointmentType',
        ),
    ]
