# Generated by Django 5.1.3 on 2025-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_appointment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='employee',
            name='scholar_id',
            field=models.CharField(blank=True, help_text='Google Scholar ID', max_length=20, null=True),
        ),
    ]
