# Generated by Django 5.1.3 on 2025-03-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_remove_employee_qualifications_employee_scholar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('book_chapter', 'Book Chapter'), ('thesis', 'Thesis'), ('report', 'Report'), ('other', 'Other')], max_length=50)),
                ('authors', models.TextField()),
                ('year', models.IntegerField()),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Entry'), ('scopus', 'Scopus'), ('orcid', 'ORCID'), ('researcherid', 'Researcher ID'), ('googlescholar', 'Google Scholar')], max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_fetched', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='employees.employee')),
            ],
        ),
    ]
