# Generated by Django 5.1.3 on 2025-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_fetched',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='journal_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='volume',
        ),
        migrations.AddField(
            model_name='publication',
            name='additional_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_type',
            field=models.CharField(choices=[('book', 'Book'), ('article', 'Journal Article'), ('booklet', 'Booklet'), ('inbook', 'In Book'), ('incollection', 'In Collection'), ('inproceedings', 'Conference Paper'), ('manual', 'Manual'), ('mastersthesis', "Master's Thesis"), ('misc', 'Miscellaneous'), ('phdthesis', 'PhD Thesis'), ('proceedings', 'Conference Proceedings'), ('techreport', 'Technical Report'), ('unpublished', 'Unpublished Work')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
