# Generated by Django 5.1.3 on 2025-02-24 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'permissions': [('can_manage_periods', 'Can manage appraisal periods')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('University Committees', 'University Committees'), ('Outside University', 'Outside University')], max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('language_medium', models.CharField(max_length=50)),
                ('no_of_students', models.IntegerField()),
                ('percentage_jointly_taught', models.FloatField()),
                ('hours_weekly', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_appointment_govt', models.DateField(blank=True, null=True)),
                ('first_appointment_ubd', models.DateField(blank=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='employees.employee')),
                ('faculty_programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.department', verbose_name='Faculty/Department')),
                ('type_of_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.appointmenttype')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('salary_scale_division', models.CharField(blank=True, max_length=50, null=True)),
                ('incremental_date', models.DateField(blank=True, null=True)),
                ('date_of_last_appraisal', models.DateField(blank=True, null=True)),
                ('academic_qualifications_text', models.TextField(blank=True, help_text='Academic qualifications details')),
                ('current_enrollment', models.TextField(blank=True, null=True)),
                ('higher_degree_students_supervised', models.TextField(blank=True, null=True)),
                ('last_research', models.TextField(blank=True, null=True)),
                ('ongoing_research', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
                ('attendance', models.TextField(blank=True, null=True)),
                ('conference_papers', models.TextField(blank=True, null=True)),
                ('consultancy_work', models.TextField(blank=True, null=True)),
                ('administrative_posts', models.TextField(blank=True, null=True)),
                ('participation_within_university', models.TextField(blank=True, null=True)),
                ('participation_outside_university', models.TextField(blank=True, null=True)),
                ('objectives_next_year', models.TextField(blank=True, null=True)),
                ('appraiser_comments', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('post_at_time_of_review', models.CharField(blank=True, max_length=100, null=True)),
                ('appointments_at_time_of_review', models.ManyToManyField(blank=True, to='appraisals.appointment')),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_appraisals', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_appraisals', to=settings.AUTH_USER_MODEL)),
                ('memberships', models.ManyToManyField(blank=True, to='appraisals.membership')),
                ('modules_taught', models.ManyToManyField(blank=True, to='appraisals.module')),
            ],
            options={
                'ordering': ['-date_created'],
                'permissions': [('can_view_all_appraisals', 'Can view all appraisals'), ('can_create_appraisal', 'Can create appraisal')],
            },
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_diploma', models.CharField(max_length=255)),
                ('university_college', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='appraisals.appraisal')),
            ],
            options={
                'ordering': ['-to_date'],
            },
        ),
    ]
