# Generated by Django 5.1.3 on 2024-11-20 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
        ('employees', '0004_department_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ['-date_created'], 'permissions': [('can_view_all_appraisals', 'Can view all appraisals'), ('can_create_appraisal', 'Can create appraisal')]},
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='appraisal_date',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='performance_rating',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='achievements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_appraisals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='areas_for_improvement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='attendance',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='communication',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='job_knowledge',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='teamwork',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='work_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee'),
        ),
    ]
