# Generated by Django 5.1.3 on 2025-03-17 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisals', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_appraisals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisalpublication',
            name='appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_publications', to='appraisals.appraisal'),
        ),
        migrations.AddField(
            model_name='appraisalpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_entries', to='employees.publication'),
        ),
        migrations.AddField(
            model_name='membership',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='module',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='employees.employee'),
        ),
    ]
