# Generated by Django 5.1.3 on 2024-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttype',
            name='name',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('MONTH-TO-MONTH', 'Month-to-Month'), ('DAILY-RATED', 'Daily-Rated')], max_length=50, unique=True),
        ),
    ]
