# Generated by Django 5.1.3 on 2025-03-18 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraiser_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_appraisals', to='employees.employee'),
        ),
        # migrations.AddField(
        #     model_name='appraisal',
        #     name='publications',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
