# Generated by Django 5.1.3 on 2024-11-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_appraisalperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisalperiod',
            options={'ordering': ['-start_date'], 'permissions': [('can_manage_periods', 'Can manage appraisal periods')]},
        ),
    ]
