# Generated by Django 5.1.3 on 2025-03-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_appraisal_appraiser_secondary_appraisal_publications'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='appraisal',
        #     name='publications',
        #     field=models.TextField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('primary_review', 'Under Primary Appraiser Review'), ('secondary_review', 'Under Secondary Appraiser Review'), ('pending_response', 'Pending Response'), ('disagreed', 'Disagreed'), ('reassigned', 'Reassigned'), ('reassigned_review', 'Under Reassigned Appraiser Review'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
