# Generated by Django 5.1.3 on 2024-12-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_alter_appointmenttype_name'),
        ('employees', '0002_remove_employee_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='employees.employee'),
        ),
    ]
