# Generated by Django 5.1.3 on 2025-03-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_appraisal_publications_alter_appraisal_status'),
        ('appraisals', '0003_appraisal_appraiser_secondary_appraisal_publications'),
        ('appraisals', '0002_initial'),
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
