# Generated by Django 5.1.3 on 2024-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_appointment_employee'),
        ('employees', '0003_appointmenttype_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='appointments_at_time_of_review',
            field=models.ManyToManyField(blank=True, to='employees.appointment'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentType',
        ),
    ]
