# Generated by Django 5.1.3 on 2024-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_alter_appraisalperiod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_appointment', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Month-to-Month', 'Month-to-Month'), ('Daily Rated', 'Daily Rated')], max_length=50)),
                ('first_appointment_govt', models.DateField(blank=True, null=True)),
                ('first_appointment_ubd', models.DateField(blank=True, null=True)),
                ('post', models.CharField(max_length=100)),
                ('faculty_programme', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('University Committees', 'University Committees'), ('Outside University', 'Outside University')], max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('language_medium', models.CharField(max_length=50)),
                ('no_of_students', models.IntegerField()),
                ('percentage_jointly_taught', models.FloatField()),
                ('hours_weekly', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_diploma', models.CharField(max_length=100)),
                ('university_college', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='job_knowledge',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='teamwork',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='work_quality',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='administrative_posts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraiser_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='conference_papers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='consultancy_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='current_enrollment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_of_last_appraisal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='higher_degree_students_supervised',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='incremental_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='last_research',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='objectives_next_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='ongoing_research',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='participation_outside_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='participation_within_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='present_post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='salary_scale_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appointments',
            field=models.ManyToManyField(blank=True, to='appraisals.appointment'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='memberships',
            field=models.ManyToManyField(blank=True, to='appraisals.membership'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='modules_taught',
            field=models.ManyToManyField(blank=True, to='appraisals.module'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='academic_qualifications',
            field=models.ManyToManyField(blank=True, to='appraisals.qualification'),
        ),
    ]
