# Generated by Django 5.1.3 on 2024-12-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0005_alter_appraisal_appointments_at_time_of_review_and_more'),
        ('employees', '0004_qualification_alter_employee_qualifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
