# Generated by Django 5.1.3 on 2025-03-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0005_fix_publications_migration_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
