# Generated by Django 5.1.3 on 2024-11-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0005_appointment_membership_module_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='academic_qualifications',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='academic_qualifications_text',
            field=models.TextField(blank=True, help_text='Academic qualifications details'),
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_diploma', models.CharField(max_length=255)),
                ('university_college', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='appraisals.appraisal')),
            ],
            options={
                'ordering': ['-to_date'],
            },
        ),
    ]
