# Generated by Django 5.1.3 on 2024-12-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_delete_qualification'),
        ('employees', '0007_alter_appointment_faculty_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_appointment_govt', models.DateField(blank=True, null=True)),
                ('first_appointment_ubd', models.DateField(blank=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='employees.employee')),
                ('faculty_programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.department', verbose_name='Faculty/Department')),
                ('type_of_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.appointmenttype')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='appointments_at_time_of_review',
            field=models.ManyToManyField(blank=True, to='appraisals.appointment'),
        ),
    ]
