# Generated by Django 5.1.3 on 2025-03-27 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_appraisal_appraisal_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='appraisals.appraisal')),
            ],
            options={
                'unique_together': {('appraisal', 'section_name')},
            },
        ),
    ]
