# Generated by Django 5.1.3 on 2024-12-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_appraisal_last_modified_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='appointments',
            new_name='appointments_at_time_of_review',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='present_post',
            new_name='post_at_time_of_review',
        ),
    ]
