# Generated by Django 5.1.3 on 2025-04-08 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_appraisalsection'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appraisalsection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appraisalperiod',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appraisalsection',
            name='appraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_sections', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='appraisalsection',
            unique_together={('appraisal', 'section_name', 'appraiser')},
        ),
    ]
