# Generated by Django 5.1.3 on 2025-02-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
