# Generated by Django 5.1.3 on 2025-05-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0008_alter_appraisalsection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('primary_review', 'Under Primary Appraiser Review'), ('secondary_review', 'Under Secondary Appraiser Review'), ('returned_to_appraisee', 'Returned to Appraisee for Revision'), ('appraisee_review', 'Appraisee Review'), ('disagreed', 'Disagreed'), ('hr_review', 'Under HR Review'), ('reassigned', 'Reassigned'), ('reassigned_review', 'Under Reassigned Appraiser Review'), ('completed', 'Completed')], default='pending', max_length=25),
        ),
    ]
