# Generated by Django 5.1.3 on 2025-02-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0008_alter_appraisal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='id',
            new_name='appraisal_id',
        ),
    ]
