# Generated by Django 5.1.3 on 2025-06-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0009_alter_appraisal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('funding_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('grants', models.CharField(blank=True, max_length=255, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_researches', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Completed Research',
                'verbose_name_plural': 'Completed Researches',
                'ordering': ['-end_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OngoingResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('funding_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('grants', models.CharField(blank=True, max_length=255, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_researches', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Ongoing Research',
                'verbose_name_plural': 'Ongoing Researches',
                'ordering': ['-end_date', 'title'],
            },
        ),
    ]
