# Generated by Django 5.1.3 on 2025-02-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0009_rename_id_appraisal_appraisal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_of_from_first_appointment_govt']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='faculty_programme',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_appointment_govt',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_appointment_ubd',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type_of_appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_from_first_appointment_govt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_from_first_appointment_ubd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_to_first_appointment_govt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_to_first_appointment_ubd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='faculty_programme_govt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Faculty/Programme'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='faculty_programme_ubd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Faculty/Programme'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_post_appointment_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_post_appointment_ubd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
