# Generated by Django 5.1.3 on 2025-02-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0010_alter_appointment_options_and_more'),
        ('employees', '0017_remove_employee_qualifications_employee_scholar_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-from_date'], 'verbose_name': 'Committee Membership', 'verbose_name_plural': 'Committee Memberships'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='incremental_date',
            new_name='incremental_date_of_present_post',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='current_enrollment',
            new_name='participation_other_activities_outside',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='participation_outside_university',
            new_name='participation_other_activities_university',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='academic_qualifications_text',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='appointments_at_time_of_review',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='memberships',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='modules_taught',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='participation_within_university',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='post_at_time_of_review',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='category',
        ),
        migrations.RemoveField(
            model_name='module',
            name='hours_weekly',
        ),
        migrations.RemoveField(
            model_name='module',
            name='language_medium',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='current_enrollment_details',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='present_post',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='committee_name',
            field=models.CharField(blank=True, help_text='Name of the committee', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='committee_type',
            field=models.CharField(blank=True, choices=[('UNIVERSITY', 'University Committees'), ('EXTERNAL', 'Outside University')], help_text='Type of committee membership', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='employees.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='hrs_weekly',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='languageMedium',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='review_period_end',
            field=models.DateField(blank=True, help_text='End date of review period', null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='review_period_start',
            field=models.DateField(blank=True, help_text='Start date of review period', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='from_date',
            field=models.DateField(blank=True, help_text='Start date of membership', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='position',
            field=models.CharField(blank=True, help_text='Position held in the committee', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='to_date',
            field=models.DateField(blank=True, help_text='End date of membership', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='no_of_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='percentage_jointly_taught',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage if jointly taught (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_source', models.CharField(blank=True, choices=[('SCHOLAR', 'Google Scholar'), ('SCOPUS', 'Scopus'), ('MANUAL', 'Manually Entered')], default='MANUAL', help_text='Source of publication data', max_length=50, null=True)),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last synchronization with external source', null=True)),
                ('title', models.CharField(help_text='Publication title', max_length=255)),
                ('authors', models.TextField(help_text='Authors (one per line or in BibTeX format)')),
                ('year', models.IntegerField(help_text='Publication year')),
                ('month', models.CharField(blank=True, help_text='Publication month', max_length=20, null=True)),
                ('publication_type', models.CharField(choices=[('JOURNAL', 'Journal Article'), ('CONFERENCE', 'Conference Paper'), ('BOOK', 'Book'), ('BOOK_CHAPTER', 'Book Chapter'), ('TECHNICAL_REPORT', 'Technical Report'), ('OTHER', 'Other')], help_text='Type of publication', max_length=50)),
                ('abstract', models.TextField(blank=True, help_text='Publication abstract', null=True)),
                ('keywords', models.CharField(blank=True, help_text='Keywords (comma-separated)', max_length=255, null=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, null=True)),
                ('url', models.URLField(blank=True, help_text='URL to publication', null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN (for books)', max_length=20, null=True)),
                ('journal_name', models.CharField(blank=True, help_text='Name of journal', max_length=255, null=True)),
                ('volume', models.CharField(blank=True, help_text='Volume number', max_length=50, null=True)),
                ('issue', models.CharField(blank=True, help_text='Issue number', max_length=50, null=True)),
                ('pages', models.CharField(blank=True, help_text='Page range (e.g., 123-145)', max_length=50, null=True)),
                ('impact_factor', models.FloatField(blank=True, help_text='Journal impact factor', null=True)),
                ('conference_name', models.CharField(blank=True, help_text='Conference name', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='Conference location', max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, help_text='Publisher name', max_length=255, null=True)),
                ('editor', models.TextField(blank=True, help_text='Editor(s)', null=True)),
                ('chapter', models.CharField(blank=True, help_text='Chapter number/name', max_length=50, null=True)),
                ('edition', models.CharField(blank=True, help_text='Edition number/name', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citation_count', models.IntegerField(default=0, help_text='Number of citations')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.DeleteModel(
            name='AcademicQualification',
        ),
    ]
