# Generated by Django 5.1.3 on 2025-06-01 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0010_completedresearch_ongoingresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_post_entries', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Administrative Post',
                'verbose_name_plural': 'Administrative Posts',
                'ordering': ['-from_date', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_attendances', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Conference Attendance',
                'verbose_name_plural': 'Conference Attendances',
                'ordering': ['-date', 'event_name'],
            },
        ),
        migrations.CreateModel(
            name='ConferencePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_paper_entries', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Conference Paper',
                'verbose_name_plural': 'Conference Papers',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsultancyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_institute', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_works', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Consultancy Work',
                'verbose_name_plural': 'Consultancy Works',
                'ordering': ['-end_date', 'title'],
            },
        ),
    ]
