# Generated by Django 5.1.3 on 2025-02-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0011_alter_membership_options_alter_module_options_and_more'),
        ('employees', '0017_remove_employee_qualifications_employee_scholar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appraisals.appraisal'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='employees.employee'),
        ),
    ]
