# Generated by Django 5.1.3 on 2025-06-01 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0011_administrativepost_conferenceattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideCommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outside_committee_memberships', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Outside Committee Membership',
                'verbose_name_plural': 'Outside Committee Memberships',
                'ordering': ['-from_date', 'organization'],
            },
        ),
        migrations.CreateModel(
            name='OutsideUniversityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outside_university_activities', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Outside University Activity',
                'verbose_name_plural': 'Outside University Activities',
                'ordering': ['-date', 'activity'],
            },
        ),
        migrations.CreateModel(
            name='UniversityCommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_committee_memberships', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'University Committee Membership',
                'verbose_name_plural': 'University Committee Memberships',
                'ordering': ['-from_date', 'committee_name'],
            },
        ),
        migrations.CreateModel(
            name='WithinUniversityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='within_university_activities', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Within University Activity',
                'verbose_name_plural': 'Within University Activities',
                'ordering': ['-date', 'activity'],
            },
        ),
    ]
