# Generated by Django 5.1.3 on 2025-02-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0012_appointment_appraisal_alter_appointment_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['code'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_from_govt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_from_ubd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_to_govt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_to_ubd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='faculty_programme_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='faculty_programme_ubd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='first_post_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='first_post_ubd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
