# Generated by Django 5.1.3 on 2025-03-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0013_alter_module_options_appraisal_date_from_govt_and_more'),
        ('employees', '0018_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.CreateModel(
            name='AppraisalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_publications', to='appraisals.appraisal')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_entries', to='employees.publication')),
            ],
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
