# Generated by Django 5.1.3 on 2025-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0014_appraisal_appraisal_year_appraisalpublication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='Publications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
