# Generated by Django 5.1.3 on 2025-03-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0015_appraisal_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='Publications',
            new_name='publications',
        ),
    ]
